// ------------------------------------------------------------------------------
//  <auto-generated>
//      Este código lo generó el generador de pruebas automatizadas de IU.
//      Versión: 15.0.0.0
//
//      Los cambios realizados en este archivo pueden provocar un comportamiento incorrecto y se perderán si
//      se vuelve a generar el código.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Web_Kactus_Test.UIMapNuevoClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public partial class UIMapNuevo
    {
        
        /// <summary>
        /// Basura
        /// </summary>
        public void Basura()
        {
            #region Variable Declarations
            WinControl uIChromeLegacyWindowDocument = this.UIKACTUSSmartPeopleGooWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Clic 'Chrome Legacy Window' documento
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(987, 603));
        }
        
        /// <summary>
        /// DocumentosCesan1: use 'DocumentosCesan1Params' para pasar parámetros a este método.
        /// </summary>
        public void DocumentosCesan1()
        {
            #region Variable Declarations
            WinPane uIKACTUSSmartPeopleGooPane = this.UIKACTUSSmartPeopleGooWindow.UIKACTUSSmartPeopleGooPane;
            WinComboBox uINombreComboBox = this.UIAbrirWindow.UIItemWindow.UINombreComboBox;
            WinButton uIAbrirButton = this.UIAbrirWindow.UIAbrirWindow1.UIAbrirButton;
            #endregion

            // Clic 'KACTUS Smart People - Google Chrome' panel
            Mouse.Click(uIKACTUSSmartPeopleGooPane, new Point(999, 645));

            // Seleccionar 'ArchivoPrueba.pdf' en cuadro combinado 'Nombre:'
            uINombreComboBox.EditableItem = this.DocumentosCesan1Params.UINombreComboBoxEditableItem;

            // Clic '&Abrir' botón
            Mouse.Click(uIAbrirButton, new Point(18, 21));
        }
        
        /// <summary>
        /// DocumentosCesan2: use 'DocumentosCesan2Params' para pasar parámetros a este método.
        /// </summary>
        public void DocumentosCesan2()
        {
            #region Variable Declarations
            WinPane uIKACTUSSmartPeopleGooPane = this.UIKACTUSSmartPeopleGooWindow.UIKACTUSSmartPeopleGooPane;
            WinComboBox uINombreComboBox = this.UIAbrirWindow.UIItemWindow.UINombreComboBox;
            WinButton uIAbrirButton = this.UIAbrirWindow.UIAbrirWindow1.UIAbrirButton;
            #endregion

            // Clic 'KACTUS Smart People - Google Chrome' panel
            Mouse.Click(uIKACTUSSmartPeopleGooPane, new Point(1010, 690));

            // Seleccionar 'ArchivoPrueba.pdf' en cuadro combinado 'Nombre:'
            uINombreComboBox.EditableItem = this.DocumentosCesan2Params.UINombreComboBoxEditableItem;

            // Clic '&Abrir' botón
            Mouse.Click(uIAbrirButton, new Point(67, 15));
        }
        
        #region Properties
        public virtual DocumentosCesan1Params DocumentosCesan1Params
        {
            get
            {
                if ((this.mDocumentosCesan1Params == null))
                {
                    this.mDocumentosCesan1Params = new DocumentosCesan1Params();
                }
                return this.mDocumentosCesan1Params;
            }
        }
        
        public virtual DocumentosCesan2Params DocumentosCesan2Params
        {
            get
            {
                if ((this.mDocumentosCesan2Params == null))
                {
                    this.mDocumentosCesan2Params = new DocumentosCesan2Params();
                }
                return this.mDocumentosCesan2Params;
            }
        }
        
        public UIKACTUSSmartPeopleGooWindow UIKACTUSSmartPeopleGooWindow
        {
            get
            {
                if ((this.mUIKACTUSSmartPeopleGooWindow == null))
                {
                    this.mUIKACTUSSmartPeopleGooWindow = new UIKACTUSSmartPeopleGooWindow();
                }
                return this.mUIKACTUSSmartPeopleGooWindow;
            }
        }
        
        public UIAbrirWindow UIAbrirWindow
        {
            get
            {
                if ((this.mUIAbrirWindow == null))
                {
                    this.mUIAbrirWindow = new UIAbrirWindow();
                }
                return this.mUIAbrirWindow;
            }
        }
        #endregion
        
        #region Fields
        private DocumentosCesan1Params mDocumentosCesan1Params;
        
        private DocumentosCesan2Params mDocumentosCesan2Params;
        
        private UIKACTUSSmartPeopleGooWindow mUIKACTUSSmartPeopleGooWindow;
        
        private UIAbrirWindow mUIAbrirWindow;
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'DocumentosCesan1'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class DocumentosCesan1Params
    {
        
        #region Fields
        /// <summary>
        /// Seleccionar 'ArchivoPrueba.pdf' en cuadro combinado 'Nombre:'
        /// </summary>
        public string UINombreComboBoxEditableItem = "ArchivoPrueba.pdf";
        #endregion
    }
    
    /// <summary>
    /// Parámetros que se van a pasar a 'DocumentosCesan2'
    /// </summary>
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class DocumentosCesan2Params
    {
        
        #region Fields
        /// <summary>
        /// Seleccionar 'ArchivoPrueba.pdf' en cuadro combinado 'Nombre:'
        /// </summary>
        public string UINombreComboBoxEditableItem = "ArchivoPrueba.pdf";
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UIKACTUSSmartPeopleGooWindow : WinWindow
    {
        
        public UIKACTUSSmartPeopleGooWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "KACTUS Smart People - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("KACTUS Smart People - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public WinPane UIKACTUSSmartPeopleGooPane
        {
            get
            {
                if ((this.mUIKACTUSSmartPeopleGooPane == null))
                {
                    this.mUIKACTUSSmartPeopleGooPane = new WinPane(this);
                    #region Criterio de búsqueda
                    this.mUIKACTUSSmartPeopleGooPane.SearchProperties[WinControl.PropertyNames.Name] = "KACTUS Smart People - Google Chrome";
                    this.mUIKACTUSSmartPeopleGooPane.WindowTitles.Add("KACTUS Smart People - Google Chrome");
                    #endregion
                }
                return this.mUIKACTUSSmartPeopleGooPane;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private WinPane mUIKACTUSSmartPeopleGooPane;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chrome Legacy Window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_RenderWidgetHostHWND";
            this.WindowTitles.Add("KACTUS Smart People - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Criterio de búsqueda
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("KACTUS Smart People - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UIAbrirWindow : WinWindow
    {
        
        public UIAbrirWindow()
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Abrir";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Abrir");
            #endregion
        }
        
        #region Properties
        public UIShellViewClient UIShellViewClient
        {
            get
            {
                if ((this.mUIShellViewClient == null))
                {
                    this.mUIShellViewClient = new UIShellViewClient(this);
                }
                return this.mUIShellViewClient;
            }
        }
        
        public UIAbrirWindow1 UIAbrirWindow1
        {
            get
            {
                if ((this.mUIAbrirWindow1 == null))
                {
                    this.mUIAbrirWindow1 = new UIAbrirWindow1(this);
                }
                return this.mUIAbrirWindow1;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIShellViewClient mUIShellViewClient;
        
        private UIAbrirWindow1 mUIAbrirWindow1;
        
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UIShellViewClient : WinClient
    {
        
        public UIShellViewClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinControl.PropertyNames.Name] = "Vista de carpetas Shell";
            this.WindowTitles.Add("Abrir");
            #endregion
        }
        
        #region Properties
        public WinList UIVistaElementosList
        {
            get
            {
                if ((this.mUIVistaElementosList == null))
                {
                    this.mUIVistaElementosList = new WinList(this);
                    #region Criterio de búsqueda
                    this.mUIVistaElementosList.SearchProperties[WinList.PropertyNames.Name] = "Vista Elementos";
                    this.mUIVistaElementosList.WindowTitles.Add("Abrir");
                    #endregion
                }
                return this.mUIVistaElementosList;
            }
        }
        #endregion
        
        #region Fields
        private WinList mUIVistaElementosList;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UIAbrirWindow1 : WinWindow
    {
        
        public UIAbrirWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1";
            this.WindowTitles.Add("Abrir");
            #endregion
        }
        
        #region Properties
        public WinButton UIAbrirButton
        {
            get
            {
                if ((this.mUIAbrirButton == null))
                {
                    this.mUIAbrirButton = new WinButton(this);
                    #region Criterio de búsqueda
                    this.mUIAbrirButton.SearchProperties[WinButton.PropertyNames.Name] = "Abrir";
                    this.mUIAbrirButton.WindowTitles.Add("Abrir");
                    #endregion
                }
                return this.mUIAbrirButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIAbrirButton;
        #endregion
    }
    
    [GeneratedCode("Generador de pruebas de UI codificadas", "15.0.26208.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Criterio de búsqueda
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "1148";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Abrir");
            #endregion
        }
        
        #region Properties
        public WinComboBox UINombreComboBox
        {
            get
            {
                if ((this.mUINombreComboBox == null))
                {
                    this.mUINombreComboBox = new WinComboBox(this);
                    #region Criterio de búsqueda
                    this.mUINombreComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Nombre:";
                    this.mUINombreComboBox.WindowTitles.Add("Abrir");
                    #endregion
                }
                return this.mUINombreComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUINombreComboBox;
        #endregion
    }
}
